-- Users table

CREATE DATABASE IF NOT EXISTS HOMESAFELY;
USE DATABASE HOMESAFELY;
SHOW DATABASES LIKE 'HOMESAFELY';

USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS USERS (
  ID STRING DEFAULT UUID_STRING() NOT NULL,
  EMAIL STRING UNIQUE,
  PASSWORD_HASH STRING,
  NAME STRING,
  ACCOUNT STRING,
  USERNAME STRING,
  AGE NUMBER(3,0),
  GENDER STRING,
  UNIVERSITY STRING,
  PROFILE_IMAGE STRING,
  IS_ONLINE BOOLEAN DEFAULT FALSE,
  LAST_SEEN TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

-- Posts table
CREATE TABLE IF NOT EXISTS POSTS (
  ID INTEGER AUTOINCREMENT PRIMARY KEY,
  USER_ID STRING NOT NULL,
  START_LAT DECIMAL(10, 8) NOT NULL,
  START_LNG DECIMAL(11, 8) NOT NULL,
  END_LAT DECIMAL(10, 8) NOT NULL,
  END_LNG DECIMAL(11, 8) NOT NULL,
  START_LOCATION VARCHAR(255),
  DESTINATION VARCHAR(255) NOT NULL,
  MODE VARCHAR(50) NOT NULL,
  RECOMMENDATION_SCORE DECIMAL(3, 2) DEFAULT 0,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Messages table
CREATE TABLE IF NOT EXISTS MESSAGES (
  ID INTEGER AUTOINCREMENT PRIMARY KEY,
  SENDER_ID STRING NOT NULL,
  RECIPIENT_ID STRING NOT NULL,
  CONTENT VARCHAR NOT NULL,
  IS_ARCHIVED BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID)
);

-- Connections table
CREATE TABLE IF NOT EXISTS CONNECTIONS (
  ID INTEGER AUTOINCREMENT PRIMARY KEY,
  USER_ID_1 S