-- Snowflake SQL Schema for HomeSafely

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  AGE INTEGER NOT NULL,
  GENDER VARCHAR(50) NOT NULL,
  PROFILE_IMAGE VARCHAR(255),
  IS_ONLINE BOOLEAN DEFAULT FALSE,
  LAST_SEEN TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Posts table
CREATE TABLE IF NOT EXISTS POSTS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL,
  START_LAT DECIMAL(10, 8) NOT NULL,
  START_LNG DECIMAL(11, 8) NOT NULL,
  END_LAT DECIMAL(10, 8) NOT NULL,
  END_LNG DECIMAL(11, 8) NOT NULL,
  DESTINATION VARCHAR(255) NOT NULL,
  MODE VARCHAR(50) NOT NULL, -- 'walking', 'uber', 'hybrid'
  RECOMMENDATION_SCORE DECIMAL(3, 2) DEFAULT 0,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Messages table for archiving chat history
CREATE TABLE IF NOT EXISTS MESSAGES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SENDER_ID INTEGER NOT NULL,
  RECIPIENT_ID INTEGER NOT NULL,
  CONTENT TEXT NOT NULL,
  IS_ARCHIVED BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID)
);

-- Connections table to track matched users
CREATE TABLE IF NOT EXISTS CONNECTIONS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID_1 INTEGER NOT NULL,
  USER_ID_2 INTEGER NOT NULL,
  POST_ID INTEGER,
  STATUS VARCHAR(50) DEFAULT 'matched',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID_1) REFERENCES USERS(ID),
  FOREIGN KEY (USER_ID_2) REFERENCES USERS(ID),
  FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)
);

-- Create indexes for better query performance
CREATE INDEX idx_posts_user_id ON POSTS(USER_ID);
CREATE INDEX idx_posts_active ON POSTS(IS_ACTIVE);
CREATE INDEX idx_posts_location ON POSTS(START_LAT, START_LNG);
CREATE INDEX idx_messages_sender ON MESSAGES(SENDER_ID);
CREATE INDEX idx_messages_recipient ON MESSAGES(RECIPIENT_ID);
CREATE INDEX idx_users_email ON USERS(EMAIL);
